// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxsunvnlhaupfazmfxld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4c3Vudm5saGF1cGZhem1meGxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxNTkyOTksImV4cCI6MjA1MzczNTI5OX0.-X7C9xtsKcR1HcYETdYjeaPQXAW9DwA0ozMxuucSPWk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);